name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      site_url:
        description: 'URL do site'
        required: true

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Obter código
      uses: actions/checkout@v4

    - name: Definir variável de ambiente SITE_URL
      run: echo "SITE_URL=${{ github.event.inputs.site_url }}" >> $GITHUB_ENV

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test
      env:
        SITE_URL: ${{ env.SITE_URL }}

    - name: Publish HTML report 
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30