name: Playwright Tests

on:
  push:             # Executa o workflow em todos os pushs
    branches: 
      - main # Especifica a branch "main" (ou outra de sua escolha)
  pull_request:        # Executa o workflow em todos os pull requests para a branch "main"
    branches: 
      - main
  workflow_dispatch:


jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Obter código
      uses: actions/checkout@v4

    - name: Definir variável de ambiente SITE_URL
      run: |
        if [[ -z "${{ github.event.inputs.SITE_URL }}" ]]; then
          echo "SITE_URL=https://www.saucedemo.com >> $GITHUB_ENV
        else
          echo "SITE_URL=${{ github.event.inputs.SITE_URL }}" >> $GITHUB_ENV
        if

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test
      env:
        SITE_URL: ${{ env.SITE_URL }}

    - name: Publish HTML report 
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
